name: Publish WinForms App

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Publish Project
        run: dotnet publish -c Release -r win-x64 --self-contained true -o publish

      - name: Upload Installer
        uses: actions/upload-artifact@v3
        with:
          name: installer
          path: publish/
